# Numpy Lab Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100. File automatically generated. See the documentation to update questions/answers/hints programmatically.



1. Import the numpy package under the name np (★☆☆)
hint: import … as

In [2]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

In [6]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

In [10]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

In [11]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

In [15]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

In [17]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
  
print ("Input  array : \n", arr)
    
out_tpl = np.nonzero(arr)
print ("Indices of non zero elements : ", out_tpl) 

Input  array : 
 [1 2 0 0 4 0]
Indices of non zero elements :  (array([0, 1, 4]),)


7. Create a 3x3 identity matrix hint: np.eye

In [19]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Create a 3x3x3 array with random values 
hint: np.random.random

In [21]:
x = np.random.random((3,3,3))
print(x)

[[[0.44141673 0.85495005 0.90318604]
  [0.39623655 0.88207347 0.82020124]
  [0.44133411 0.87367215 0.22816965]]

 [[0.6712788  0.01969787 0.49092507]
  [0.96002875 0.72885112 0.1884892 ]
  [0.25642447 0.29195514 0.65368554]]

 [[0.20866517 0.81321841 0.20125771]
  [0.90091212 0.07503575 0.82568576]
  [0.58271685 0.19155728 0.44899526]]]


9. Create a 10x10 array with random values and find the minimum and maximum values 
hint: min, max

In [23]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.96151322 0.97867693 0.02155984 0.16613212 0.22805608 0.81865575
  0.415656   0.49095175 0.93477308 0.32970762]
 [0.85307415 0.96005197 0.63396068 0.02445885 0.93479867 0.57846682
  0.22431634 0.27392944 0.70581797 0.99955413]
 [0.27731076 0.8288548  0.73485606 0.80167827 0.96834584 0.37379866
  0.77947957 0.60056513 0.19237294 0.53034343]
 [0.13920481 0.89005013 0.04740811 0.0658663  0.9938482  0.927962
  0.20969099 0.82571771 0.31671185 0.39408724]
 [0.68986141 0.0767365  0.98091395 0.836426   0.42378036 0.09572694
  0.44601475 0.66956166 0.37889269 0.78675486]
 [0.31634933 0.59988541 0.61600015 0.36566403 0.27915503 0.94058283
  0.40974737 0.90056297 0.15484481 0.63542465]
 [0.34558968 0.1374005  0.43557689 0.62027388 0.44227683 0.59726402
  0.89420265 0.39130233 0.266421   0.75782887]
 [0.57182057 0.20284701 0.37402033 0.08325864 0.50401824 0.66581571
  0.47824684 0.35805909 0.30143726 0.04566068]
 [0.87542431 0.06861198 0.23004626 0.85095637 0.88810334 0.3386308

10. Create a random vector of size 30 and find the mean value 
hint: mean

In [34]:
x = np.random.random(30)
print("Original array:")
print(x)
np.mean(x)

Original array:
[0.29061454 0.64363965 0.13867828 0.60020904 0.44688239 0.23138894
 0.57575783 0.10396474 0.62741164 0.22764927 0.11843595 0.93644035
 0.09767653 0.58457198 0.9488134  0.1778644  0.06945954 0.10611446
 0.60724096 0.43473416 0.75183128 0.88124698 0.2149029  0.75021395
 0.66687728 0.47116288 0.47552669 0.00885142 0.43053149 0.04611402]


0.4221602313096064

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
hint: np.diag

In [29]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


12. Normalize a 5x5 random matrix 
hint: (x -mean)/std

In [31]:
df= np.random.random((5,5))
print("Original Array:")
print(df)
dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
print(df)

Original Array:
[[0.87429315 0.02035378 0.38489613 0.35736894 0.54025917]
 [0.68529817 0.49448349 0.49115109 0.94172735 0.2255861 ]
 [0.33188081 0.85687327 0.11599611 0.81822917 0.89012468]
 [0.28939513 0.2515919  0.74461544 0.36876432 0.56483291]
 [0.79405246 0.43867379 0.32645037 0.72728242 0.03506244]]
[[0.92681123 0.         0.39565098 0.36577472 0.5642721 ]
 [0.72168815 0.51459009 0.51097332 1.         0.22274605]
 [0.33811153 0.9079048  0.10380408 0.86596297 0.94399376]
 [0.29200029 0.25097108 0.78606733 0.37814254 0.59094285]
 [0.83972312 0.45401781 0.33221768 0.76725518 0.01596384]]


13. How to find common values between two arrays? 
hint: np.intersect1d

In [33]:
x = np.array([0, 1, 2, 3, 4])
y = [1, 3, 4]
  
# Common values between two arrays
print(np.intersect1d(x, y))

[1 3 4]


14. Create a random vector of size 10 and sort it 
hint: sort

In [37]:
x = np.random.random(10)
print(x)
x.sort()
print(x)

[0.11074996 0.20882419 0.3205199  0.5292046  0.92975514 0.63410419
 0.98634098 0.49850218 0.35114581 0.33501637]
[0.11074996 0.20882419 0.3205199  0.33501637 0.35114581 0.49850218
 0.5292046  0.63410419 0.92975514 0.98634098]


15. Create random vector of size 10 and replace the maximum value by 0 
hint: argmax

In [41]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.36375726 0.12891779 0.38369817 0.14076317 0.63906952 0.87992764
 0.59321067 0.94610562 0.74465886 0.18725144]
[0.36375726 0.12891779 0.38369817 0.14076317 0.63906952 0.87992764
 0.59321067 0.         0.74465886 0.18725144]


16. Subtract the mean of each row of a matrix 
hint: mean(axis=,keepdims=)

In [44]:
x = np.random.rand(5, 6)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.24911721 -0.62428864  0.24218817 -0.12240924  0.13734994  0.11804255]
 [ 0.20688667  0.03486784 -0.105595    0.08111978 -0.21250441 -0.00477488]
 [-0.11160975 -0.09142553 -0.32556948 -0.02340794  0.39269376  0.15931894]
 [-0.36460307 -0.43911163  0.4232491  -0.09781692  0.13340709  0.34487544]
 [ 0.46734738  0.33161933 -0.18925132 -0.28931454  0.1159289  -0.43632975]]


17. How to get the n largest values of an array 
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [50]:
arr = np.arange(10000)
np.random.shuffle(arr) 
n = 5
sorted_index_array = np.argsort(arr)
sorted_array = arr[sorted_index_array]
print(sorted_array)
rslt = sorted_array[-n : ]
print(rslt)

[   0    1    2 ... 9997 9998 9999]
[9995 9996 9997 9998 9999]


18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [62]:
x = np.random.randint(0,10, (5, 3))
print(x)
y = np.where(x < 4, x, x**2)
print(y)

[[2 1 6]
 [0 9 3]
 [1 0 4]
 [5 1 9]
 [2 3 5]]
[[ 2  1 36]
 [ 0 81  3]
 [ 1  0 16]
 [25  1 81]
 [ 2  3 25]]
